name: TwoShipsPassingInTheNight

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan secrets avec Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    needs: secret-scan
    runs-on: ubuntu-latest
    steps:
      - name: Ca clone sur la machine du runner GitHub.
        uses: actions/checkout@v4

      - name: Installe Node.js sur la machine du runner GitHub.
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Cava dans le dosier ca installe est ca fais les tests.
        run: |
          cd TwoShipsPassingInTheNight
          npm install
          npm test

  push_to_mirror:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Push vers le miroir Epitech
        run: |
          git remote add mirror https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/EpitechWebAcademiePromo2027/W-DOP-200-MLN-2-1-jeux_videops-2.git
          git push mirror main






   